const fs = require('fs');
let code = fs.readFileSync('prisma/seed.ts', 'utf8');
code = code.replace(/prisma\.prodi/g, 'prisma.department');
code = code.replace(/prisma\.fakultas/g, 'prisma.faculty');
code = code.replace(/prodis:/g, 'departments:');
code = code.replace(/prodiId/g, 'departmentId');
code = code.replace(/fakultasId/g, 'facultyId');
code = code.replace(/scope: 'universitas'/g, "scope: 'university'");
code = code.replace(/scope: 'fakultas'/g, "scope: 'faculty'");
code = code.replace(/scope: 'prodi'/g, "scope: 'department'");
fs.writeFileSync('prisma/seed.ts', code);
